"""Log mapper adapter: discover modules and log paths, generate .md sorted by content."""

from __future__ import annotations

import re
from collections import defaultdict
from pathlib import Path
from typing import Any


def discover_logs_and_modules(project_root: Path) -> dict[str, Any]:
    modules = sorted(_find_modules(project_root))
    logs_by_content = _categorize_logs(project_root)
    map_path = project_root / ".e2e-test-plugin" / "e2e-map.md"
    map_path.parent.mkdir(parents=True, exist_ok=True)

    lines = [f"# E2E Map: {project_root.name}", "", "## Modules", ""]
    for module in modules:
        lines.append(f"- `{module}`")
    lines.extend(["", "## Logs by Content", ""])
    for category, paths in sorted(logs_by_content.items()):
        lines.append(f"### {category}")
        for path in paths:
            lines.append(f"- `{path}`")
        lines.append("")
    lines.extend(["", "## Content Summary", "", "_Auto-generated by e2e-test-plugin._"])
    map_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {
        "modules": modules,
        "logs_by_content": {k: v for k, v in sorted(logs_by_content.items())},
        "map_path": str(map_path),
        "status": "ok",
    }


def _find_modules(project_root: Path) -> list[str]:
    modules: list[str] = []
    for path in sorted(project_root.rglob("*.py")):
        if _is_ignored(path, project_root):
            continue
        rel = path.relative_to(project_root)
        text = path.read_text(encoding="utf-8", errors="ignore")
        if "def main(" in text or "__main__" in text or 'if __name__ == "__main__"' in text:
            modules.append(str(rel))
    return modules


def _categorize_logs(project_root: Path) -> dict[str, list[str]]:
    categories: dict[str, list[str]] = defaultdict(list)
    for path in sorted(project_root.rglob("*")):
        if path.is_file() and not _is_ignored(path, project_root) and _looks_like_log(path):
            rel = path.relative_to(project_root)
            category = _categorize_log_content(path)
            categories[category].append(str(rel))
    return dict(sorted(categories.items()))


def _categorize_log_content(path: Path) -> str:
    name = path.name.lower()
    if ".jsonl" in name or name.endswith(".json"):
        return "JSON Logs"
    if name.endswith(".log") or "log" in name:
        return "Text Logs"
    if "events" in name:
        return "Event Streams"
    if name.endswith(".md"):
        return "Markdown Reports"
    return "Other Artifacts"


def _looks_like_log(path: Path) -> bool:
    name = path.name.lower()
    if any(token in name for token in ["log", "logs", ".jsonl", ".json", "events"]):
        return True
    if path.suffix.lower() in {".log", ".jsonl", ".json"}:
        return True
    return False


def _is_ignored(path: Path, project_root: Path) -> bool:
    rel = path.relative_to(project_root)
    parts = set(rel.parts)
    ignore = {".venv", "__pycache__", ".git", "node_modules", ".mypy_cache", ".ruff_cache"}
    return bool(parts & ignore)
