"""Discover modules and log paths, then write an e2e-map.md sorted by content."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any


def discover_logs_and_modules(project_root: Path) -> dict[str, Any]:
    modules = sorted(_find_modules(project_root))
    logs = sorted(_find_logs(project_root))
    map_path = project_root / ".e2e-test-plugin" / "e2e-map.md"
    map_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# E2E Map: {project_root.name}",
        "",
        "## Modules",
        "",
    ]
    for module in modules:
        lines.append(f"- `{module}`")
    lines.extend(["", "## Logs", ""])
    for log in logs:
        lines.append(f"- `{log}`")
    lines.extend(["", "## Content Summary", "", "_Auto-generated by e2e-test-plugin._"])
    map_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {
        "modules": modules,
        "logs": logs,
        "map_path": str(map_path),
        "status": "ok",
    }


def _find_modules(project_root: Path) -> list[str]:
    modules: list[str] = []
    for path in sorted(project_root.rglob("*.py")):
        if _is_ignored(path, project_root):
            continue
        rel = path.relative_to(project_root)
        text = path.read_text(encoding="utf-8", errors="ignore")
        if "def main(" in text or "__main__" in text or 'if __name__ == "__main__"' in text:
            modules.append(str(rel))
    return modules


def _find_logs(project_root: Path) -> list[str]:
    logs: list[str] = []
    for path in sorted(project_root.rglob("*")):
        if path.is_file() and not _is_ignored(path, project_root) and _looks_like_log(path):
            rel = path.relative_to(project_root)
            logs.append(str(rel))
    return logs


def _is_ignored(path: Path, project_root: Path) -> bool:
    rel = path.relative_to(project_root)
    parts = set(rel.parts)
    ignore = {".venv", "__pycache__", ".git", "node_modules", ".mypy_cache", ".ruff_cache"}
    return bool(parts & ignore)


def _looks_like_log(path: Path) -> bool:
    name = path.name.lower()
    if any(token in name for token in ["log", "logs", ".jsonl", ".json", "events"]):
        return True
    if path.suffix.lower() in {".log", ".jsonl", ".json"}:
        return True
    return False
